# Generated by Django 3.1.3 on 2021-06-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_categories',
            field=models.ManyToManyField(blank=True, related_name='post_related_categories', to='blog.PostCategory', verbose_name='Связанные категории'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_gallery',
            field=models.ManyToManyField(blank=True, related_name='post_related_gallery', to='blog.Gallery', verbose_name='Связанные галереи'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_post_related_posts_+', to='blog.Post', verbose_name='Связанные публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_tags',
            field=models.ManyToManyField(blank=True, related_name='post_related_tags', to='blog.Tag', verbose_name='Связанные тэги'),
        ),
    ]
