# Generated by Django 3.1.3 on 2021-06-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210628_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
