# Generated by Django 3.1.3 on 2021-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210629_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
