# Generated by Django 3.1.3 on 2021-07-01 11:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_gallery_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='most_popular',
            field=models.BooleanField(default=False, verbose_name='Отобразить на главной'),
        ),
        migrations.AddField(
            model_name='post',
            name='full_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
