# Generated by Django 3.1.3 on 2021-07-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210701_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='most_popular',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
    ]
