# Generated by Django 3.1.3 on 2021-09-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210725_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description_ukr',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_ukr',
        ),
    ]
