# Generated by Django 3.1.3 on 2022-07-03 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210919_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_text_ukr',
            field=ckeditor.fields.RichTextField(verbose_name='Полный текст укр'),
        ),
    ]
