# Generated by Django 3.1.3 on 2021-06-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='attachent_type',
            new_name='attachment_type',
        ),
    ]
