# Generated by Django 3.1.3 on 2021-07-03 00:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210701_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название вакансии')),
                ('icon', models.ImageField(upload_to='', verbose_name='Заставка вакансии')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='user',
            name='characteristic',
            field=models.TextField(blank=True, null=True, verbose_name='О преподавателе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_statement',
            field=models.TextField(blank=True, null=True, verbose_name='Название программ'),
        ),
    ]
