# Generated by Django 3.1.3 on 2021-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210703_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ('order',), 'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
