# Generated by Django 3.1.3 on 2021-07-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210704_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='order',
        ),
    ]
