# Generated by Django 3.1.3 on 2021-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210704_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='ФИО родителя')),
                ('profession', models.CharField(max_length=50, verbose_name='Профессия')),
                ('parent_image', models.ImageField(upload_to='', verbose_name='Аватарка родителя')),
                ('comment', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий родителя',
                'verbose_name_plural': 'Комментарии родителей',
            },
        ),
    ]
