# Generated by Django 3.1.3 on 2021-07-06 07:33

import core.utils.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_parentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcomment',
            name='parent_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=core.utils.utils.user_avatar, verbose_name='Аватарка родителя'),
        ),
    ]
