# Generated by Django 3.1.3 on 2021-07-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_maincounters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincounters',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Символ после числа'),
        ),
    ]
