# Generated by Django 3.1.3 on 2021-07-06 09:44

import core.utils.utils
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_aboutcounters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preview_avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=core.utils.utils.user_avatar, verbose_name='Картинка в маленьком блоке'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
    ]
