# Generated by Django 3.1.3 on 2021-07-07 19:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210706_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcomment',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Профессия'),
        ),
        migrations.CreateModel(
            name='DropDownPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_page', models.BooleanField(default=True, verbose_name='Отобразить на главной?')),
                ('opened', models.BooleanField(default=False, verbose_name='Развернут')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mеnu_cat', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='users.dropdownpoint', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Раскрывающийся пункт',
                'verbose_name_plural': 'Раскрывающиеся пункты',
            },
        ),
    ]
