# Generated by Django 3.1.3 on 2022-07-03 14:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210725_0052'),
        
    ]
    initial = True
    operations = [
        migrations.AddField(
            model_name='program',
            name='hours_ukr',
            field=models.TextField(default='', verbose_name='Часы проведения программы ukr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание русский'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='full_text_ukr',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание украинский'),
        ),
    ]
