# Generated by Django 3.1.3 on 2022-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220703_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='characteristic_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='О преподавателе ukr'),
        ),
        migrations.AddField(
            model_name='user',
            name='fio_ukr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО  ukr'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_statement_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='Название программ ukr'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='Специализация ukr'),
        ),
    ]
