# Generated by Django 3.1.3 on 2021-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210628_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ManyToManyField(related_name='event_category', to='lessons.LessonCategory', verbose_name='Категория зантия'),
        ),
    ]
