# Generated by Django 3.1.3 on 2021-07-01 11:15

import ckeditor.fields
import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210701_1115'),
        ('lessons', '0005_auto_20210629_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Возрастная группа мероприятия', 'verbose_name_plural': 'Возрастные группы мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='lessoncategory',
            options={'verbose_name': 'Возрастная группа занятия', 'verbose_name_plural': 'Возрастные группы занятий'},
        ),
        migrations.AddField(
            model_name='event',
            name='full_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='full_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='most_popular',
            field=models.BooleanField(default=False, verbose_name='Отобразить на главной'),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(upload_to=models.ImageField(upload_to=core.utils.utils.preview, verbose_name='Картинка в блоке'), verbose_name='Картинка на странице'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(related_name='event_related_gallery', to='blog.Gallery', verbose_name='Выбрать фото из галереи'),
        ),
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.ImageField(upload_to=core.utils.utils.preview, verbose_name='Картинка в блоке'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='background_image',
            field=models.ImageField(upload_to=models.ImageField(upload_to=core.utils.utils.preview, verbose_name='Картинка в блоке'), verbose_name='Картинка на странице'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ManyToManyField(related_name='lesson_category', to='lessons.LessonCategory', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_start',
            field=models.TextField(blank=True, null=True, verbose_name='Дата начала занятий группы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='gallery',
            field=models.ManyToManyField(related_name='lesson_related_gallery', to='blog.Gallery', verbose_name='Выбрать фото из галереи'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(upload_to=core.utils.utils.preview, verbose_name='Картинка в блоке'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(verbose_name='Url part'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(related_name='lesson_related_tags', to='blog.Tag', verbose_name='Тэги группы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок группы'),
        ),
    ]
