# Generated by Django 3.1.3 on 2021-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210701_1251'),
        ('lessons', '0006_auto_20210701_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='event_related_gallery', to='blog.Gallery', verbose_name='Выбрать фото из галереи'),
        ),
        migrations.AlterField(
            model_name='event',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='event_related_posts', to='blog.Post', verbose_name='Схожие посты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='event_related_tags', to='blog.Tag', verbose_name='Тэги мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(verbose_name='Класс фильтра категории'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_time',
            field=models.TextField(verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='lesson_related_gallery', to='blog.Gallery', verbose_name='Выбрать фото из галереи'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lesson_related_tags', to='blog.Tag', verbose_name='Тэги группы'),
        ),
        migrations.AlterField(
            model_name='lessoncategory',
            name='slug',
            field=models.SlugField(verbose_name='Класс фильтра категории'),
        ),
    ]
