# Generated by Django 3.1.3 on 2021-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20210701_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='discount_fee',
            field=models.TextField(blank=True, null=True, verbose_name='Цена абонемента со скидкой'),
        ),
    ]
