# Generated by Django 3.1.3 on 2021-07-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lesson_discount_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн формат'),
        ),
    ]
