# Generated by Django 3.1.3 on 2021-07-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн формат'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='event_category', to='lessons.EventCategory', verbose_name='Категория мероприятия'),
        ),
    ]
