# Generated by Django 3.1.3 on 2021-07-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_event_most_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='Заголовок вопроса')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('right', models.BooleanField(default=False, verbose_name='Отобразить в правой колонке?')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
