# Generated by Django 3.1.3 on 2021-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20210706_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TextField(verbose_name='Окончание'),
        ),
    ]
