# Generated by Django 3.1.3 on 2021-07-25 00:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20210707_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_text_ukr',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=100, null=True, verbose_name='Заголовок события ukr'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='title_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=100, null=True, verbose_name='Заголовок категории ukr'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ukr',
            field=models.TextField(help_text='Украинская версия', null=True, verbose_name='Ответ ukr'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=150, null=True, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='class_time_ukr',
            field=models.TextField(help_text='Украинская версия', null=True, verbose_name='Расписание ukr'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=100, null=True, verbose_name='Заголовок группы ukr'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='title_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=100, null=True, verbose_name='Заголовок категории ukr'),
        ),
    ]
