# Generated by Django 3.1.3 on 2021-09-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20210901_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title_ukr',
        ),
        migrations.AddField(
            model_name='lesson',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discount_fee',
            field=models.TextField(blank=True, null=True, verbose_name='Цена абонемента со скидкой'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='try_lesson',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробное занятие'),
        ),
    ]
