# Generated by Django 3.1.3 on 2021-06-28 03:29

import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок события')),
                ('preview', models.ImageField(upload_to=core.utils.utils.preview, verbose_name='Preview')),
                ('background_image', models.ImageField(upload_to=models.ImageField(upload_to=core.utils.utils.preview, verbose_name='Preview'), verbose_name='Фон')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
