# Generated by Django 3.1.3 on 2021-07-16 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210716_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
