# Generated by Django 3.1.3 on 2021-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20210717_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
