# Generated by Django 3.1.3 on 2021-07-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_order_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_archive',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Загружаемый файл'),
        ),
    ]
