# Generated by Django 3.1.3 on 2021-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_product_download_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='datetime_end',
            field=models.DateTimeField(help_text='Дата окончания дейстивя купона', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='datetime_start',
            field=models.DateTimeField(help_text='Дата начала дейстивя купона', null=True, verbose_name='Дата начала'),
        ),
    ]
