# Generated by Django 3.1.3 on 2021-07-25 00:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20210724_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ukr',
            field=models.TextField(help_text='Украинская версия', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_text_ukr',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title_ukr',
            field=models.CharField(help_text='Украинская версия', max_length=100, null=True, verbose_name='Заголовок товара'),
        ),
    ]
