# Generated by Django 3.1.3 on 2021-09-19 13:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20210725_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='О товаре'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_text_ukr',
            field=ckeditor.fields.RichTextField(verbose_name='О товаре Укр'),
        ),
    ]
